# Streamlit Cloud Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your actual values

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"
OPENAI_MODEL = "gpt-4o"

# Transcripts Directory (for deployment)
TRANSCRIPTS_DIR = "/app/transcripts" 